modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/yuuki1293/KeymapPresets/issues"
license = "MIT"

[[mods]]
modId = "keymappresets"
version = "${version}"
displayName = "KeymapPresets"
authors = "yuuki1293"
description = '''
Create key mapping presets and recall them at any time.
'''
logoFile = "assets/keymappresets/icon.png"

[[dependencies.keymappresets]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.keymappresets]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.keymappresets]]
modId = "architectury"
mandatory = true
versionRange = "[4.11.93,)"
ordering = "AFTER"
side = "BOTH"
